services:

  postgres:
      image: postgres
      restart: always
      container_name: postgres
      #command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: test
        PGDATA: /var/lib/postgresql/data
      volumes:
      - ./data:/var/lib/postgresql/data
      ports:
      - '5432:5432'

  pgadmin4:
      image: elestio/pgadmin
      restart: always
      container_name: pgadmin
      depends_on: 
        - postgres
      environment:
        PGADMIN_DEFAULT_EMAIL: kcahow@gmail.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 8080
      ports:
      - "8080:8080"
      volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./pgadmin_data:/pgadmin
